#!/usr/bin/env node
/**
 * The battlecard is GENERATED — `npm run generate`, checked by the `generated` gate.
 *
 * The argument for generating it is the one this project already applies to types and the access
 * matrix: **durable claims are written down, everything derivable is computed.** A competitive
 * document is mostly derivable, and the parts that are not are small and identifiable.
 *
 *   Derived here          the spec's real status and criteria counts · every evidence link, resolved
 *                         and verified to exist · the verification command · which rows exist at all
 *   Written by a person   the claim, the comparison, the argument, the one-line version
 *
 * The split matters because the two rot differently. A hand-copied status is wrong within a week and
 * nothing notices; an argument does not go stale on a schedule and cannot be produced by a template.
 * Generating the first and hand-writing the second is the only division that survives contact.
 *
 * **What this does NOT do is decide whether a claim is true.** It resolves citations. A claim whose
 * evidence resolves can still be wrong, and no generator fixes that — which is why `check-content`
 * demands evidence be a finding id or a path rather than a sentence.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';

const MANIFEST = 'docs/content/MANIFEST.json';
const FRAGMENTS = 'docs/content/differentiators';
const OUT = 'docs/content/BATTLECARD.md';
const SPEC_DIR = 'spec';

/** A spec's real state, read from the spec rather than from anyone's memory of it. */
export function specState(text) {
  const status = (text.match(/^> Status: `(\w+)`/m) ?? [, '?'])[1];
  const reqs = (text.match(/^### REQ-/gm) ?? []).length;
  const acs = [
    ...text.matchAll(/^\|\s*AC-[\w.]+\s*\|[^|]*\|[^|]*\|[^|]*\|\s*\*{0,2}([\w -]+?)\*{0,2}\s*\|/gm),
  ].map((m) => m[1].trim());
  return {
    status,
    reqs,
    acs: acs.length,
    done: acs.filter((a) => a === 'done').length,
    deferred: acs.filter((a) => /^deferred/i.test(a)).length,
  };
}

/** An evidence token becomes a link a reader can follow, or the build fails. */
export function evidenceLink(token, exists) {
  if (/^F-\d+$/.test(token)) return `[${token}](../FINDINGS.md)`;
  if (!exists(token)) return null;
  const depth = '../../';
  return `[\`${token}\`](${depth}${token})`;
}

/**
 * Pure. The whole document, from structured fields plus hand-written fragments.
 * @returns {string}
 */
export function render({ manifest, specs, fragments, exists }) {
  const out = ['# Battlecard', ''];
  out.push(
    '<!-- GENERATED by scripts/battlecard.mjs — do not edit. The argument for each row lives in',
    '     docs/content/differentiators/, the structured fields in docs/content/MANIFEST.json. -->',
    '',
  );
  out.push(fragments._preamble.trim(), '', '---', '');

  for (const d of manifest.differentiators ?? []) {
    const state = specs[d.spec];
    const fragment = fragments[d.spec];
    if (!fragment) throw new Error(`${d.spec}: no argument fragment at ${FRAGMENTS}/${d.spec}.md`);

    out.push(`## ${d.battlecard}`, '');
    out.push(`**What keelblock claims.** ${d.claim}`, '');
    out.push(`**What the field does instead.** ${d.rivals}`, '');
    out.push(fragment.trim(), '');

    const links = (d.evidence ?? []).map((e) => {
      const link = evidenceLink(e, exists);
      if (!link) throw new Error(`${d.spec}: evidence \`${e}\` does not resolve`);
      return link;
    });
    out.push(`**Evidence:** ${links.join(' · ')}`, '');

    if (state) {
      // Derived, so it cannot describe a spec that has moved on without it.
      const parts = [`${d.spec} is \`${state.status}\``, `${state.reqs} requirements`];
      parts.push(
        state.deferred
          ? `${state.done} of ${state.acs} criteria met, ${state.deferred} deferred with a reason`
          : `${state.done} of ${state.acs} criteria met`,
      );
      out.push(`**State.** ${parts.join(' · ')}. Verify: \`npm run check\`.`, '');
    }
    if (d.oneLine) out.push(`**The one-line version.** ${d.oneLine}`, '');
    out.push('---', '');
  }

  out.push(fragments._closing.trim(), '');
  return out.join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));
  const specs = Object.fromEntries(
    readdirSync(SPEC_DIR)
      .filter((f) => /^SPEC-\d+/.test(f))
      .map((f) => [f.slice(0, 8), specState(readFileSync(`${SPEC_DIR}/${f}`, 'utf8'))]),
  );
  const fragments = Object.fromEntries(
    readdirSync(FRAGMENTS)
      .filter((f) => f.endsWith('.md'))
      .map((f) => [f.replace(/\.md$/, ''), readFileSync(`${FRAGMENTS}/${f}`, 'utf8')]),
  );

  let generated;
  try {
    generated = render({ manifest, specs, fragments, exists: (p) => existsSync(p) });
  } catch (err) {
    console.error(`battlecard: FAILED\n\n  ${err.message}\n`);
    process.exit(1);
  }

  const committed = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (!check) {
    writeFileSync(OUT, generated);
    console.log(`battlecard: written — ${(manifest.differentiators ?? []).length} row(s)`);
    return;
  }
  if (committed !== generated) {
    console.error(
      `${OUT} is STALE — a spec's status, a claim or an argument has changed since it was ` +
        `generated.\n    The published comparison would describe a product that has moved.\n` +
        `    Regenerate and read the diff:  npm run generate`,
    );
    process.exit(1);
  }
  console.log('battlecard: current');
}

if (import.meta.url === `file://${process.argv[1]}`) main();
