#!/usr/bin/env node
/**
 * The README's state block — generated, never written down.
 *
 * **Why this exists.** `README.md` is the most-read file in the repository and, until this, the one
 * with the least protection. It has now been wrong in both directions about the same paragraph:
 * F-82 found it calling shipped work unbuilt for nine days, and a later audit found it listing
 * passkeys, 2FA and email verification — none of which appear anywhere in `src/` — under a heading
 * that reads as shipped.
 *
 * The rule this project already lives by is that **durable claims are written down and volatile
 * state is computed**. Which capabilities exist is volatile state. `docs/content/BATTLECARD.md`
 * already treats it that way and cannot drift; the README was asserting the same class of fact by
 * hand. So this generates the block, and `check-generated.mjs --check` byte-compares it, exactly as
 * it does for the access matrix and the battlecard.
 *
 * **No second walk.** The spec catalog comes from `census()` in `status.mjs` — the same reader
 * `npm run status` uses. A parallel parse would be a second place for the answer to be different,
 * which is the class F-78 charged for twice.
 *
 * What this does NOT do: judge prose. "Why this exists" is an argument, not a state, and a gate that
 * tried to check it would be guessing in the direction of confidence (F-82's reason for declining
 * one). This replaces only the region between the markers.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { census } from './status.mjs';

const OUT = 'README.md';
const BEGIN = '<!-- BEGIN:generated:state -->';
const END = '<!-- END:generated:state -->';

/**
 * `spec/SPEC-007-billing.md` -> `Billing`. The title a reader would recognise, from the file.
 * @param {string} id
 * @param {(p: string) => string} [read]
 * @param {string[] | null} [list] spec filenames, passed in so this never walks the tree itself
 * @returns {string}
 */
export function titleOf(id, read = (p) => readFileSync(p, 'utf8'), list = null) {
  const files = list ?? [];
  const file = files.find((f) => f.startsWith(id));
  if (!file) return id;
  const first = read(`spec/${file}`).split('\n')[0];
  return (first.match(/^#\s*SPEC-\d+:\s*(.+)$/) ?? [, id])[1].replace(/`/g, '').trim();
}

/**
 * The block, from the catalog.
 *
 * Three groups, and the middle one is the honest part most status blurbs omit: a spec can be
 * genuinely half-built, and saying so is the difference between this file and a brochure.
 *
 * @param {{specs: Array<{id: string, status: string, acs: string[]}>}} c
 * @param {string[]} specFiles
 * @param {(p: string) => string} read
 */
export function render(c, specFiles, read = (p) => readFileSync(p, 'utf8')) {
  const name = (s) => `${titleOf(s.id, read, specFiles)}`;
  const done = (s) => s.acs.filter((a) => a === 'done').length;

  const built = c.specs.filter((s) => s.status === 'done');
  const partial = c.specs.filter((s) => s.status === 'partial');
  const draft = c.specs.filter((s) => s.status === 'draft');

  const line = (xs, fmt) => xs.map(fmt).join(' · ');

  return [
    BEGIN,
    '',
    '<!-- Generated by scripts/readme-state.mjs from the spec catalog. Do not edit by hand: change',
    '     the spec, then `npm run generate`. The `generated` gate byte-compares this block. -->',
    '',
    '**Built, with every acceptance criterion met:**',
    '',
    line(built, (s) => `${name(s)} (\`${s.id}\`)`) || '_none yet_',
    '',
    '**Partly built** — the criteria still open are listed in each spec:',
    '',
    line(partial, (s) => `${name(s)} (\`${s.id}\`, ${done(s)} of ${s.acs.length})`) || '_none_',
    '',
    '**Specced and not built** — these are a plan, not a product:',
    '',
    line(draft, (s) => `${name(s)} (\`${s.id}\`)`) || '_none_',
    '',
    'Anything not named above is not specced either. `npm run status` computes this list; if it ever',
    'disagrees with the block above, the block is stale and the build fails.',
    '',
    END,
  ].join('\n');
}

/** Replace the marked region. Refuses rather than guessing if the markers are missing or crossed. */
export function replaceBlock(doc, block) {
  const start = doc.indexOf(BEGIN);
  const end = doc.indexOf(END);
  if (start === -1 || end === -1) {
    throw new Error(
      `README.md is missing the ${BEGIN} / ${END} markers. The state block is generated; ` +
        `deleting its markers would silently return the file to hand-maintained claims, which is ` +
        `the defect this exists to prevent (F-82).`,
    );
  }
  if (end < start) throw new Error('README.md has its generated-state markers in the wrong order.');
  return doc.slice(0, start) + block + doc.slice(end + END.length);
}

function main() {
  const check = process.argv.includes('--check');
  const specFiles = readdirSync('spec').filter((f) => /^SPEC-\d+/.test(f));
  const block = render(census(), specFiles);
  const committed = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  const next = replaceBlock(committed, block);

  if (!check) {
    writeFileSync(OUT, next);
    console.log('readme-state: written');
    return;
  }
  if (committed !== next) {
    console.error(
      `${OUT}'s generated state block is STALE — a spec's status or acceptance criteria have ` +
        `changed since it was written.\n    The most-read file in the repository is describing a ` +
        `product that has moved.\n    Regenerate and read the diff:  npm run generate`,
    );
    process.exit(1);
  }
  console.log('readme-state: ok');
}

if (import.meta.url === `file://${process.argv[1]}`) main();
